# -*- coding: utf-8 -*-
"""Scrapping facebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E-mqgZWvaVyJvrwWYyW_n1po9er4rbMq
"""

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import bs4
from pprint import pprint
import json

#Initialization method. 
chrome_options = webdriver.ChromeOptions()

# chrome_options.add_argument('--headless') #for pop up windows
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-setuid-sandbox')

# Open Browser
driver = webdriver.Chrome("chromedriver", options=chrome_options)

#Akses Facebook dengan browser yang sudah dibuka
akun_name = "abddul.hamied"
base_url = 'https://www.facebook.com/{}/'.format(akun_name)
driver.get(base_url)

akun = bs4.BeautifulSoup(driver.page_source, 'lxml')
driver.close()

def parser_facebook_akun(post):
    tab_nama = akun.find("a", {"class":"_2nlw _2nlv"})
    nama = tab_nama.text

    tab_pekerjaan = akun.find("div", {"class":"_2lzr _50f5 _50f7"})
    pekerjaan = tab_pekerjaan.text

    tab_pendidikan = akun.findAll("ul", {"class":"uiList fbProfileEditExperiences _4kg _4ks"})[1].findAll("li", {"class":"_43c8 _5f6p fbEditProfileViewExperience experience"})
    sekolah = []
    for pend in tab_pendidikan:
        sekolah.append(pend.text)

    tab_kota_sekarang = akun.findAll("ul", {"class":"uiList fbProfileEditExperiences _4kg _4ks"})[2].find("li", {"id":"current_city"}).find("span", {"class":"_2iel _50f7"})
    kota_sekarang = tab_kota_sekarang.text

    tab_kota_asal = akun.findAll("ul", {"class":"uiList fbProfileEditExperiences _4kg _4ks"})[2].find("li", {"id":"hometown"}).find("span", {"class":"_2iel _50f7"})
    kota_asal = tab_kota_asal.text

    tab_tentang = akun.findAll("ul", {"class":"uiList fbProfileEditExperiences _4kg _4ks"})[3].find("span", {"class":"_c24 _2iem"})
    tentang = tab_tentang.text
    dict_akun = {"nama":nama, "pekerjaan":pekerjaan, "pendidikan":sekolah, 
                 "kota sekarang":kota_sekarang, "kota asal":kota_asal, "tentang":tentang}
    return dict_akun

parser_facebook_akun(akun)

#Mendapatkan Info Lengkap dari Akun Tersebut
tab_nama = akun.find("a", {"class":"_2nlw _2nlv"})
nama = tab_nama.text

tab_pekerjaan = akun.find("div", {"class":"_2lzr _50f5 _50f7"})
pekerjaan = tab_pekerjaan.text

tab_pendidikan = akun.findAll("ul", {"class":"uiList fbProfileEditExperiences _4kg _4ks"})[1].findAll("li", {"class":"_43c8 _5f6p fbEditProfileViewExperience experience"})
sekolah = []
for pend in pendidikan:
    sekolah.append(pend.text)
    
tab_kota_sekarang = akun.findAll("ul", {"class":"uiList fbProfileEditExperiences _4kg _4ks"})[2].find("li", {"id":"current_city"}).find("span", {"class":"_2iel _50f7"})
kota_sekarang = tab_kota_sekarang.text

tab_kota_asal = akun.findAll("ul", {"class":"uiList fbProfileEditExperiences _4kg _4ks"})[2].find("li", {"id":"hometown"}).find("span", {"class":"_2iel _50f7"})
kota_asal = tab_kota_asal.text

tab_tentang = akun.findAll("ul", {"class":"uiList fbProfileEditExperiences _4kg _4ks"})[3].find("span", {"class":"_c24 _2iem"})
tentang = tab_tentang.text

dict_akun = {"nama":nama, "pekerjaan":pekerjaan, "pendidikan":sekolah, 
             "kota sekarang":kota_sekarang, "kota asal":kota_asal, "tentang":tentang}
dict_akun

def saving_doc(clean_post,doc='txt'):
    doc = doc.lower()
    if doc == 'txt':
        with open('data_clean.txt', 'w') as f:
            print(clean_post, file=f)
    elif doc == 'json':
        doc = doc.upper()
        with open('data_clean.JSON', 'w') as file:
             file.write(json.dumps(clean_post))
    else:
        print('Unsupported document')      
    print('Document succes saving as dataclean.{}'.format(doc))

saving_doc(dict_akun,doc='json')

